#create a aws codebuild project to build nextjs app
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Running pre-build tasks..."
  build:
    commands:
      - echo "Building the Next.js app..."
      - npm run build
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: 'out' 
