version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Enabling pnpm via Corepack..."
      - corepack enable
      - corepack prepare pnpm@latest --activate
      - echo "Setting pnpm store directory for caching..."
      - pnpm config set store-dir /root/.pnpm-store
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pnpm install --frozen-lockfile
  build:
    commands:
      - echo "Building static export..."
      - pnpm run build
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  base-directory: "out"
  files:
    - "**/*"

cache:
  paths:
    - "/root/.pnpm-store/**/*"
    - "node_modules/**/*"